server:
  port: 9011

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: trading-monitor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    liquibase:
      enabled: true
      drop-first: false
      change-log: classpath:db/changelog/db.changelog-master.yaml
      default-schema: public
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    url: jdbc:postgresql://${DB_HOST}/trading-monitor

springdoc:
  swagger-ui:
    path: /swagger-ui.html

secret-key: ${SECRET_NUMBER}

algorithm: ${ALGORITHM}

quant:
  url: ${QUANT_URL}