--liquibase formatted sql

--changeset a.khaustov:1

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Corresponds to @Id, @GeneratedValue, Long id
    external_id BIGINT, -- Corresponds to @Column(name = "external_id"), Long externalId
    username VARCHAR(255), -- Corresponds to @Column(name = "username"), String username
    credentials VARCHAR(500) -- Corresponds to @Column(name = "credentials"), String credentials
);